from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent

BROKER = "mqtt.protonest.co"
PORT = 8883

DEVICE_NAME = "YOUR_DEVICE_NAME"
MQTT_CLIENT_ID = DEVICE_NAME
MQTT_USERNAME = DEVICE_NAME
MQTT_PASSWORD = "YOUR_MQTT_PASSWORD"

STATE_NAME = "motor"
ACK_STATE_NAME = "last-command"
CA_CERT_PATH = BASE_DIR / "certs" / "root-ca.crt"

CONNECT_TIMEOUT_SECONDS = 15
RECONNECT_DELAY_SECONDS = 5
POLL_INTERVAL_SECONDS = 0.2
