#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define DEVICE_NAME "YOUR_DEVICE_NAME"

#define PROTONEST_MQTT_HOST "mqtt.protonest.co"
#define PROTONEST_MQTT_PORT 8883
#define PROTONEST_MQTT_URI "mqtts://" PROTONEST_MQTT_HOST ":8883"

#define PROTONEST_APP_VERSION "0.0.1"

#define PROTONEST_WIFI_MAXIMUM_RETRY 15
#define PROTONEST_MQTT_RECONNECT_DELAY_MS 5000
#define PROTONEST_STATUS_PUBLISH_DELAY_MS 1500
#define PROTONEST_ROLLBACK_CONFIRM_DELAY_MS 5000
#define PROTONEST_ROLLBACK_VERIFY_TIMEOUT_MS 60000

#define PROTONEST_LED_PIN 13
#define PROTONEST_LED_BLINK_INTERVAL_MS 100

#define PROTONEST_MQTT_BUFFER_SIZE 2048
#define PROTONEST_OTA_TASK_STACK_SIZE 12288
