WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"

BROKER = "mqtt.protonest.co"
PORT = 8883

DEVICE_NAME = "YOUR_DEVICE_NAME"
MQTT_CLIENT_ID = DEVICE_NAME

STREAM_NAME = "temperature"
MQTT_CA_DER_PATH = "/certs/root-ca.der"
DEVICE_CERT_PATH = "/certs/device-cert.der"
DEVICE_KEY_PATH = "/certs/device-key.der"

WIFI_CONNECT_TIMEOUT_SECONDS = 30
MQTT_KEEPALIVE_SECONDS = 60
RECONNECT_DELAY_SECONDS = 5
PUBLISH_INTERVAL_SECONDS = 5
