#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define DEVICE_NAME "YOUR_DEVICE_NAME"

#define PROTONEST_MQTT_HOST "mqtt.protonest.co"
#define PROTONEST_MQTT_PORT 8883
#define PROTONEST_MQTT_URI "mqtts://" PROTONEST_MQTT_HOST ":8883"

#define PROTONEST_STREAM_NAME "temperature"
#define PROTONEST_PUBLISH_INTERVAL_MS 5000

#define PROTONEST_WIFI_MAXIMUM_RETRY 15
#define PROTONEST_MQTT_RECONNECT_DELAY_MS 5000
