WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"

BROKER = "mqtt.protonest.co"
PORT = 8883

DEVICE_NAME = "YOUR_DEVICE_NAME"
MQTT_CLIENT_ID = DEVICE_NAME

MQTT_CA_DER_PATH = "/certs/root-ca.der"
DEVICE_CERT_PATH = "/certs/device-cert.der"
DEVICE_KEY_PATH = "/certs/device-key.der"
HTTPS_CA_DER_PATH = "/certs/http-root-ca.der"

APP_PATH = "/app.py"
APP_BACKUP_PATH = "/app_prev.py"
TEMP_DOWNLOAD_PATH = "/download.tmp"
OTA_STATE_PATH = "/ota_state.json"

APP_VERSION = "0.0.1"
MAX_PENDING_BOOTS = 5
WIFI_CONNECT_TIMEOUT_SECONDS = 30
MQTT_KEEPALIVE_SECONDS = 60
RECONNECT_DELAY_SECONDS = 5
MQTT_POLL_INTERVAL_SECONDS = 0.2
DOWNLOAD_SOCKET_TIMEOUT_SECONDS = 15
MAX_HTTP_REDIRECTS = 3
APP_CRASH_REBOOT_DELAY_SECONDS = 2
