WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"

BROKER = "mqtt.protonest.co"
PORT = 8883

DEVICE_NAME = "YOUR_DEVICE_NAME"
MQTT_CLIENT_ID = DEVICE_NAME
MQTT_USERNAME = DEVICE_NAME
MQTT_PASSWORD = "YOUR_MQTT_PASSWORD"

STATE_NAME = "motor"
ACK_STATE_NAME = "last-command"
MQTT_CA_DER_PATH = "/certs/root-ca.der"

WIFI_CONNECT_TIMEOUT_SECONDS = 30
MQTT_KEEPALIVE_SECONDS = 60
RECONNECT_DELAY_SECONDS = 5
MQTT_POLL_INTERVAL_SECONDS = 0.2
